### ISSUE TITLE
Kick command doesn’t work

### ISSUE THREAD

**Issue by groveld** [groveld/discord-bot#23]
The kick command has no action, it only sends a message in reply but doesn't actually tries and kick a user.

src/commands/moderation/kick.js

**Comment by ELECTROISLIVE** [comment]
when it will be fixed

**Comment by groveld** [comment]
The bot has the ability to kick now.
It doesn't check the permissions of the user calling the kick yet, so all users can kick everybody....
I have already created a new ticket addressing this issue.
